# C-c C-c  "F:/baiduyundownload/Dropbox/Emacs/ToDo/remember/diary.org" -> "* %g"
# C-u C-c C-c  like C-c C-c, and immediately visit note at target location
# C-0 C-c C-c  "???" -> "* ???"
# C-1 C-c C-c  to select file and header location interactively.
# C-2 C-c C-c  as child (C-3: as sibling) of the currently clocked item
# To switch templates, use `<f12>'.  To abort use `C-c C-k'.

* 2013
** 12月December
*** 今天继续折腾了一天的emacs，
感觉第二次折腾，比第一次远远容易上手得多，只是对lisp语言，不认识，太多的命令，不认识，也不知道表示
的是什么含义，可是折腾的速度，比以前要远远块很多了。
而且，这一次，一个个的突破，感觉要顺畅的多，也不会盲目的把所有别人的配置文件都放到自己这里来
目前我有的配置文件有：
|      |               |
|------+---------------|
| mew  | 邮件          |
| org  | 文本编辑，GTD |
| w3m  | 浏览网页      |
| emms | 听歌          |

<2013-12-09 周一> 
 
*** 完善emacs 的 emms， org-mode，  
Entered on [2013-12-09 周一 19:18]
 
  
Entered on [2013-12-09 周一 19:20]
 
** 2013-12 十二月
*** 2013-12-09 星期一
**** emacs : org-mode
     know the way how to use emacs, and the way to use org-mode.
     to use it ,and to use it ...... 
Entered on [2013-12-09 周一 19:27]
 
 [[file:f:/baiduyundownload/Dropbox/Emacs/ToDo/newgtd.org]]
**** listen to the 今晚80后
     the speaker can talk for a long time ,but , in the life time,he can be a good 
talking?
I am not a talkative,i can learn from him and remember the joke in the radio.
and talk to the people in the dayly time.
Entered on [2013-12-09 周一 20:10]
*** 2013-12-10 星期二
**** 模仿者学写毕业论文
     今天按照计划写毕业论文的系统实现部分，也就是论文第四章。
     系统架构和界面算是完成了一大部分，功能上没有去实现。思路和架构有了一部分，只是怎么去实现却还是不太清楚。
     按照李兰师姐的论文结构和表述，将自己的论文思路加入到他的论文当中。写了好半天，发现才几百个字，而论文需要三万字以上。。。
     今天大体要把第四章的主要表现内容写出来，比如：系统的架构，系统的界面，系统选择的模型和表现的方式有哪些。
     需要沉下心来写东西了。。。

     今天打球，给自己定的计划是半小时，可是当自己下楼，开始打球，却又停不下来，看到羽毛球，感兴趣，看到乒乓球，手痒，各种不安分。
     当我一个人站在场外，没人打理的时候，自己居然还是不肯走，还磨磨蹭蹭的想过去打球。。。
     完全不顾自己的计划，以后要牢记！说多久，就多久！给自己定时间！
Entered on [2013-12-10 周二 19:32]

*** 2013-12-11 星期三
**** 折腾了一天的图标
     程序的界面设计，大体上都是靠ribbon的图标撑出来的。首先是ribbon的图标很大，其次是需要涉及的功能很多，按钮的触发，事件的相应。
     - 首先：明确ribbon分为几类，模型，数据库，操作，表现等。
     - 其次：每个图标都要唯一的ID用来识别。每个图标对应的图片也要有唯一的PIC_ID号。
     - 第三：ID号和PIC_ID号相对应
     - 第四：ID号和对应的程序也要想匹配，这就要求需要用到全局的变量来识别。

     今天遇到的问题：首先是用WingIDE无法解析图标图片到base64格式。
     - 问题描述：执行pic2base64程序，提示 module no attributes name "encodestring"
     - 网上找的答案是：the name of the file can not be "base64.py"
     - 修改后，还是不能解决。于是只好自己动手修改源代码了。既然是找不到这个程序，那我就把这个程序加入进来，还好这个程序涉及的其他类只有一个。
     - 添加完毕：执行：OK！折腾了我一下午的东西，终于好了。。。写个日记，记录下来。只是自己不知道原因。。
Entered on [2013-12-11 周三 19:12]
 
*** 2013-12-12 星期四
**** 存在运气这个东西吗？
     生活中，我们大体会经常听到，唉，今天运气真不好，又怎么怎么了。。然后会指出一大堆的理由来支撑他的观点，最后得出结论，今天的所有不好都是因为自己的运气不够好，
每次听到这样的话，自己确实都有些不屑。再加上那些所谓的成功学的“经典”著作，让我知道理由大多时候都是站不住脚的。
     可今天的事情，让我不得不相信，运气，有时候真的是个说不清的东西。
     讲述下今天的事情把：在完成了程序中的一个小模块 以后，我就兴高采烈的下楼打球去了。一切也从打球开始的。
     今天大师兄在实验室，我不方便拿自己的球拍下去打球，于是只好問同学借了他的球拍。一切都相安无事，然后我和同学的球拍突然相撞在一起，当时还没有什么事情，
然后在随后的几次重力击球后，发现球拍不对劲，拿起来看，发现已经变形了，也就是坏了。
     这是运气不好的第一点。当时觉得赔个球拍把，本命年，运气不好，破财消灾。。。
     可是，接下来打球的过程中，我居然连着被同学重力击中了两次。整场球下来，就我被打过。。。这让我心中很是郁闷啊。。。
     话虽说，本命年运气不好，也不至于都发生在我一个人身上吧。。。 
     
     打球回来后，主动跟同学提出，给他买个新的，同学拒绝了，说：也该到坏的时候了，已经很多年了。。。
     很不好意思，说邀请他吃饭，他也没有表示，估计看我主动不主动了，我也觉得不够诚意，突然看到桌上的巧克力，就说晚上请他吃巧克力。哈哈。
如此一来，也就算解决了。

    虽说本命年运气不够好，可是人品还是在的。。不是因为没有赔钱高兴，而是因为有这样的同学。。。
Entered on [2013-12-12 周四 16:52]
*** 2013-12-13 星期五
**** 打羽毛球
     打羽毛球，已经有大约三年时间了把。时间在我球技增长中度过了，从以前什么都不会，到现在能打个后场，吊个前场，勾个对角了。
     又是一个下午打球的时间，跟地科院本科生的会长打球，原本他是比我差一点点的，随着他成为会长，每周参加社团的活动开始，技术就噌噌噌的上来了，比我高出一头。
     今天再次和他打球，心情很舒畅，毫无压力，球路也就打的很开，拉拉后场，反手勾个对角，批掉一个前场，好不畅快。
     羽毛球，见证了我的研究生生活，从我们班第一个买球拍，到被老板指责，到参加比赛，再到认识别人。
     一路走来，陪伴我，体恤我，不离不弃的守着我。
     因为他，我受过伤（扭到过脚），也因为他，我差点被老板剔除实验室组，也因为他，我认识了很多朋友，因为他，我获得了研究生第一个奖项（研究生羽毛球赛亚军），
因为他，我锻炼了身体，因为他，我排遣了压力。。。
     他成为了我的爱好，也许，也成了我一辈子最喜欢的运动把。
     不管曾经他给我带来了什么，我都会坚持我对羽毛球的喜爱，
Entered on [2013-12-13 周五 17:25]
*** 2013-12-15 星期日
**** 折腾手机+emacs
     花了一晚上看了十集足球小子，呵呵学会一句话，不一定要有天赋，只要有激情，把喜欢的东西当作朋友，时时刻刻的抱着他，疼着他不放手，自然会获得回报的。
     手机，是因为很卡，很卡，所以想把那些新软件都换成旧的，可是折腾了很久又变成刷系统了。。。。真是手贱。。。。
     emacs，同学跟我提了一个clock check的功能，又是手贱，又想弄懂一下这个功能，觉得这个功能不错，又想调整自己的设置。。。各种折腾，
Entered on [2013-12-15 周日 23:31]
 
 [[file:~/ToDo/newgtd.org]]
*** 2013-12-16 Monday
**** 老板谈工作
     一大早，老板就到实验室来了，跟我们聊聊工作的事情。似乎跟他最近升了副院长有关系把。
     老板总结了每个人的性格，适合的工作，对未来的的规划。
     这里就说说对我的评价把：**你就不适合吹嘘拍马的工作，以后做领导的可能性不是没有，但是即使到了那个位置，但也会很累。
     因为领导并不是每天坐在那里跟每个人聊天就行了，需要对整个发展有一个把握，学院每个人要往哪里走，都要做好设定。更重要的是有霸气。
     而我，不够自信，不能喝酒，嘴也不甜。肯定是不适合做行政的了。只能靠自己的本事来吃饭，虽然不一定穷，但是肯定相对很累。
     总结：每个人不一定要有大成就，重要的是活的开心，找准自己的定位，扬长避短。

     PS：你工作，最开始一段时间，只要是交代给你的任务就要做到！不管是你接触没接触过的。再难，再累，都要努力完成，让人对你第一印象好，以后就好办多了。
         如果开始就总是推迟，那想重新建立别人对你的印象就很难了。
Entered on [2013-12-16 Mon 15:17]
 
 [[file:~/ToDo/newgtd.org]]
*** 2013-12-21 Saturday
**** 不折腾，不知道限制的原因
- MongoDB说在32位的电脑上，不支持大于2G的数据库，现在看来，真的限制很大。
我存储一个300M的CSV文件，则会报错，“数据库内存不足”然后就自动关闭了。
只有64位的系统才能不受这个条件的限制。
- 在插入数据库的时候，CSV 转 dict的时候也会出生各种错误，比如csv读取的时候，分割符号
不一定是","  , 也可能是"tab" , 所以在读取csv的时候，需要设置"rU"的读取模式才会默认强制转换为同一样的分隔符。
- 在存储数据库的时候，又出现了 csv转为dict的时候，存在key = none的情况，即key不是string。
这样也就不能够存储到MongoDB中了。这时候采用try except 方法+if条件判断，过滤掉不合格的数据。
这样就能把不合格的东西过滤掉。
- 又因为32位的限制， 所以只能采用分段存储的方式，一个数据库只能存储2G，所以必须分为几个数据库来存储。
最开始我采用一个数据库，几个集合来存储，发现这样是不行的。后来限制读取数据的数量，还是会发生错误。
32位的环境确实限制太多了。无奈，只能安装SQL server来配置了。嘻嘻。
- 学习，有时候就是要尝试各种情况，才知道哪个数据库真的好，存在哪些缺陷，在哪些方面很好。
Entered on [2013-12-21 Sat 09:26]
 
 [[file:~/ToDo/newgtd.org]]
**** 折腾一天的Python shape格式
     python里面比较难处理的两个东西，一个是中文编码。一个就是字符串的格式了。
     - 编码问题由来已久，到现在为止也没办法很好的解决，不管什么时候都会碰到几个不能解决的编码。
     - 今天主要问题出现在字符串编码格式上。
从dict到JSON，到shapely的shape格式。三种格式之间的转换，真够纠结的。因此也记录下来。
dict格式是Python里面比较通用，也比较常用的格式。兼容性非常好，除了key必须是string类型外，其他的毫无要求。
JSON格式就比较严格了，string前面不能有u字符， string必须以双引号（“）包围起来。
shape格式则主要是为了利用shapely库的运算 ，不得不讲格式转换到shapely认可的格式中来。
具体的步骤如下：
- 从MongoDB中读取数据，格式为dict
- 引入json库，利用json.dumps方法，将dict转为Json格式
- 引入shapely的shape库，利用shapes(json.loads(JSON)）方法，讲Json格式转为shape格式。
至此，就可以很好的利用shapely的各种方法了。


Entered on [2013-12-21 Sat 19:21]
*** 2013-12-22 星期日
**** 今天又折腾了一天的emacs
     目的+内容+工具 = 完成任务。
     目的，是完成这个任务的最终目标，所有的一切都是为了这个目的而为的。不管是学什么内容，还是用什么样的工具
这些都是为了目的而服务的。所以，首先，做一切的出发点，就是这个目的。如果目的不明确，千万别乱折腾，只是浪费时间而已。
     内容：这是支撑目的的血肉之躯，是完成一切目的的表现形式。是否达到了目的，做到什么程度，都是内容来表现的。
这时候，就需要考虑，我们需要什么样的表现形式去支撑这个内容的东西。不管是图片，还是文档。
     工具，就是最后的基础，是支撑内容的基石。没有人说这不重要，只是在不能完成某个目的的前提下，工具，永远是排在最后一位的。
所以，很多人争辩过：到底这么折腾工具，有好处吗？其实不同的人，确实有不同的答案。有的人喜欢这样，有的人喜欢那样的工具。
这个工具为了简单，这个工具特点是美观，这个工具为了效率，不可能去满足每个人的要求的。
     emacs，确实是值得折腾的工具，在没有目的的前提下，emacs，确实没有什么值得折腾的东西。
在win下折腾，在cygwin下折腾，其实都是一样的。哪个方便，就用哪个。没必要去为了那可能用不上的目的去利用那个cygwin。
     最终又回到了win的怀抱。因为，emacs，所有的东西，都只是配置而已。保存了配置了，想什么时候重新利用都是可以的。

     折腾好了，graphviz，latex，这样就好多了。。。不会出现各种奇怪的错误了。
Entered on [2013-12-22 周日 22:36]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/remember/diary.org::*%E4%B8%8D%E6%8A%98%E8%85%BE%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E9%99%90%E5%88%B6%E7%9A%84%E5%8E%9F%E5%9B%A0][不折腾，不知道限制的原因]]
*** 2013-12-23 星期一
**** 真正要汇报了
     研究生，三年过了，这次，可能是唯一的 一次大组汇报把。
真正要到了汇报的时候，自己才知道自己真的什么都没有做。不管是毕业论文，还是其他东西，似乎我都没有做到。
研究更是谈不上的，任何方向的研究。。。
     实验室的他们在讨论着可视化，讨论着台风，讨论着时空轨迹，讨论着几何代数，讨论着大数据分析，。。。
而我，不知道自己做了什么。。。完全做了个没有什么理论基础的东西。
     下午，和师兄聊天，说了下论文的东西，又顺了下思路，自己又想了下应该要出的图是什么，
每个章节应该要做些什么图片，要写些什么东西。。。
只是真的要把这些东西写到大组汇报中，实在找不到可以写的东西。系统，确实没有什么理论基础可以说的。
只能用系统出的分析图来展示下自己做的东西，但是这些都确实没有什么意义啊。。。
     
     真正要有一个方向，才能带一群人。真正到现在才知道，如果没有方向，要给一个实验室的所有人都给定一个方向，
这件事情确实很有难度，需要担负的责任和考虑的事情就多了。
     从宏观上去考虑，分析，确定方向，才能让人学习有明确的方向，怎么获取方向，就需要对现在的新科技发展有一定的了解
对现在的国内，国外的研究有一定的认知。而要做到这些东西，就需要经常看优秀的论文，看高等级的论文，熟知现在的最新科技
公司的新发展。

     而我，从来都没有这么做过。只有到了现在才知道，自己三年过了，都没有真正的知道研究到底是怎么回事。

     三年，基本上都是一个人在折腾，在乱七八糟的学着乱七八糟的东西，没有人告诉过我这些东西，没有同学讨论过这些东西，
也没有同学跟我说过这些东西。。。只有自己知道，才真正的知道晚了。

     找到工作了，都不知道自己会什么东西。。现在，只能让自己多反思，每天写下自己这一天的反思。
     
     今天实验第一次不上QQ，专心的做东西，真的，效率提高了很多。只是没有好好的反省。

     准备一个本子，写下来今天要反思的东西把。。。。
Entered on [2013-12-23 周一 22:31]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E3%80%8A%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB%E6%BA%90%E4%BB%A3%E7%A0%81%E3%80%8B][《如何阅读源代码》]]
*** 2013-12-26 星期四
**** 第四章的基本思路
- 确定模型
  - 江苏省多要素空间模糊综合评价
- 准备数据
  - excel数据
    - 2009年，江苏省各市GDP
    - 人口数据
  - shp数据
    - DEM数据 ： 江苏省栅格化数据
    - 土地利用类型 ： 土地利用斑块图，包括农地，耕地，林地等
    - 居民点分布 ： 各市居民点分布数据
    - 道路路网数据 ： 道路格网各等级数据，包括：国道，省道，市道
    - 水域河网数据 ： 水域，河流，湖泊等水体空间分布数据
    - 生态数据 ： 生态敏感区和非敏感区
- 模型流程
  - 确定对象集，即研究范围：江苏省 ， 各市
  - 确定综合评价指标：（人口，GDP，土地利用，道路交通，水域河网，生态环境，居民点分布
  - 建立综合评价指标权重集：人口 0.2， GDP 0.2，土地利用 0.1，道路交通 0.2，水域河网0.1，生态环境0.1，居民点分布0.1
  - 建立综合评价级别：下滑，平稳，快速增长
  - 建立评价矩阵：
  - 执行评价函数：
  - 绘制等级图：
- 编写函数
  - 
- 出图
  - 
Entered on [2013-12-26 周四 21:47]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org]]
*** 2013-12-27 星期五
**** 只有实践，才知道学什么
     实践是检验真理的唯一标准，这放之四海而皆准，
     很早以前，我一直只是觉得，他就是一个教条的话语，要我们相信，真理和实践的关系，相信，这句话可以得分。
     最近，自己忙着毕业论文，也忙着师兄突然而来的任务，突然发现以前没有接触到的东西，一下子全都冒出来了。
     以前不知道python可以完成这么多自己认为很难的工作，包括去除重复，统计重复频率，等等。
     也不知道wxpython界面，也可以实现各种乱七八糟的功能，包括图标拖拽。
     
     实践的前提，是目标，目标的前提，是理论支撑。
     理论是指导实践工作的，实践又重新更正理论知识。
     多么正确的道理啊。以前从来没有往自己身上考虑过。
     理论，也就是做这件事情的出发点，也就是站在什么层次去考虑，解决这个问题。
     有的人是码农，因为他站在程序可执行，并得到结果的角度考虑编程的作用。
     有的人是项目经理，因为他站在项目的高度，去考虑每个模块要实现的功能，系统要实现的功能。
     有的人是策划，因为他站在客户的角度，去考虑，这个系统应该要实现什么功能，应该怎么去实现。
     有的人则是CEO，因为他站在公司的角度，去考虑这个项目是否能够为公司带来利益，带来多大的利益。

     而在实现这一切的前提下，就是实践，一层层的传递，最后由码农反馈回去消息，再向上层层的提升。
     也就是由下而上（具体化的过程），再由下而上（抽象化的过程），这样周而复始。最终实现这个产品。

     从我自身而言，做这个系统前，是毫无理论基础可言的，只是老师说，应该要怎么做，也就是项目经理对码农说的：
     你要实现这个函数，和那个函数的对接，并调用数据库。
     好吧，我就照这样去做了。

     后来，发现，这一切并不是这么回事，实现功能的前提是我自身的能力，也是项目描述基础。老师从来也没有跟我说，是什么函数，
     又是什么数据，这一切都是模糊的。发现此路不通啊。。。

     没办法，从新去看理论知识，看看别人怎么去解决这个问题，问老师，这个东西的出发点，理论架构在哪里。。
     慢慢的，一条稍微清晰的脉络出来了，
     只是，这个系统，是架构在什么层次上的东西，为什么要做这个东西，怎么做到这一切的，我还不是太清楚。
     这个系统，是为了模型而生的，也是为了数据而生的。我就是要架构两者之间的桥梁，通过模型来搜寻数据，最后又应用到模型。

     以后，做事情，首先考虑一定的理论基础，然后心无旁骛的去做，去实践。。一次次的实践，一次次的更正理论。。。
Entered on [2013-12-27 周五 23:13]
 
 [[file:d:/cygwin/home/jerryfive/Text/module.org::*%E7%AC%AC%E5%9B%9B%E7%AB%A0%E7%9A%84%E5%9F%BA%E6%9C%AC%E6%80%9D%E8%B7%AF][第四章的基本思路]]
* 2014
** 2014-01 一月
*** 2014-01-01 星期三
**** 师姐回来和我们一起过元旦
     宗真师姐，毕业半年有余了，在扬州工作，也有将近半年了把。元旦放假之际，偕同老公同回学校看望实验室的同学，大伙都觉得很高兴。
前一天，师姐就告知我，她想来学校看看大家。心中不免高兴，也把这个消息跟实验室的同学说了。大伙都兴奋的问道：师姐什么时候来呢？我见过吗？足见关心之情。

    元旦了，师姐十点多就到了学校，在实验室和我们聊得热火。似乎她一点都没有变化，工作的艰辛，社会的阴暗，生活的压力，都没有能在她身上留下半点印记。
没感觉成熟，也没感觉不妥。说话还是那样的直爽。谈及工作，直道学校和公司，相距甚远，压力也大，做的事情，也全然是重复性的劳动。初时，还觉得增长甚块，到得后来，便觉索然无味。

    不知不觉，就到饭点，各位寻思着该去哪里吃饭好，大伙说：师姐难得来一次，提议就去外面吃吧。东城汇。走起！
    等了约莫半个多小时，终于轮到了我们了。有过了大约十几分钟，菜也终于闷好了。只曾听闻的：黄记煌闷锅。
    席间，大伙吃的火热，聊天也就不是很多了。只到下午两点多，才吃完散场。
    师姐的老公，开车过来的，车内只能乘坐四，五人，可在场9人，不可全坐，只能分头行动了。
    如此这般，这个元旦，就匆匆和师姐吃了个中餐，就早早的散场，连道别的话都没有来得及说。
    真不知她是怎样的心情。。。。
Entered on [2014-01-01 周三 23:15]
 
 [[file:d:/cygwin/home/jerryfive/Text/2012summarize.org::*]]
*** 2014-01-02 星期四
**** 开始了2014年的正式学习的第一天
     2014年，按我自己的计划走着。
     用五笔来打字，用emacs来记录日记，写org-gtd，写反思，等等。
     也开始每天的锻炼，这样的生活，也是不错的。
     不和寝室的同学说没用的东西，也不去争无谓的口舌。
     2014，还要好好 的做好计划。为自己的未来打基础。
Entered on [2014-01-02 周四 22:05]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%5B#A%5D%20%E5%AE%8C%E6%88%90%E8%AE%BA%E6%96%87%E7%AC%AC%E5%9B%9B%E7%AB%A0%EF%BC%88%E5%8E%9F%E5%9E%8B%E7%B3%BB%E7%BB%9F%E5%AE%9E%E7%8E%B0%EF%BC%89][完成论文第四章（原型系统实现）]]
*** 2014-01-03 星期五
**** 认真的看网页信息
     org mode 确实很强大,我对它的要求是:
     - 需要统计每天,每周的 tags 时间 ,
     - 需要统计每周的 类别 时间.
     - 任务完成放到 achive 中.achive中的任务按datetree 排列.
     - 
     CLOCK: [2014-01-03 周五 20:02]--[2014-01-03 周五 20:08] =>  0:06
Entered on [2014-01-03 周五 20:02]
*** 2014-01-04 星期六
**** GTD是什么
     GTD是指导你做什么的工具. 
     写好你要做的东西,然后,你按时间要求去做这些事,就好了.
     其他比如统计,都是你做到这些后要做的事情.
     不要太关心这些东西.
     做自己真的要做的事情,才是GTD的真谛...
     CLOCK: [2014-01-04 周六 14:12]--[2014-01-04 周六 14:14] =>  0:02
Entered on [2014-01-04 周六 14:12]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E6%9D%A8%E4%B9%A6%E8%AE%B0%E7%9A%84%E8%B0%88%E8%AF%9D%E6%94%B9%E4%B8%BA19%E5%8F%B7%E4%B8%8B%E5%8D%88%E4%B8%80%E7%82%B9][杨书记的谈话改为19号下午一点]]
*** 2014-01-06 星期一
**** 生活没有想像的难
     我们都在做着，做着，，，似乎总有做不完的事情。
     自己也是一直在做，做。然后，当自己要写总结的时候，都不知道从哪里写起。这就是大部分的时间都交代给了没用的事情。
     昨天做好了emacs，想好了自己应该怎么去用这个软件，这样才从内心中接受了他，也才会挥发它的作用。

     emacs，要实现什么样的功能呢？
     1. 能够做好统计。给做的每个事情都统计好。每周的，每天的，每月的，每个类型的。
     2. 能够做每月的，每周的，每天的计划。
     3. 
     CLOCK: [2014-01-06 周一 09:18]--[2014-01-06 周一 09:26] =>  0:08
Entered on [2014-01-06 周一 09:18]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%89][写日记（10分钟）]]
*** 2014-01-07 星期二
**** 坚持第二天
     这是第二天按自己的计划来走。发现了，自己的计划中还是存在了一些问题。这里记下来。
1. 早上的任务安排过重了。应该分开来做。比如读书，早上要用去40多分钟的时间。
2. 可以把一些事情放到晚上去做（读书，背单词）
3. 一些琐屑的事情不能记录（这个不重要）
   昨天要汪旭帮我做了个小软件，功能很简单，介绍如下：
4. 新建按钮，添加事件名称
5. 点击按钮，确定是否记录当前时间
6. 长按按钮，确定是否删除当前按钮
7. 列表查看记录的时间
8. 导出记录为txt文档
   我还想要增加一个统计的功能，介绍如下：
9. 生成一周，一月，一年的统计图
10. 每个事件生成一个统计图
11. 所有事件生成一个总的统计图
 

Entered on [2014-01-07 周二 09:53]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%89][写日记（10分钟）]]
*** 2014-01-08 星期三
**** 打球就忘记时间
     自我感觉　,我在打球上还是有点感觉的.不管是球感,还是反应,都不算很差.当然,天赋肯定是没有的.
只是喜欢,然后就坚持,到现在的有点疯狂.
昨天遇到个高手,也说不上高手吧,比我还差点.就忍不住的想要打球了.
一开始打球,就忘记时间了.从开始到结束,我用了将近3个小时的时间.

这个,如果硬要说到最开始的原因,还是QQ.
如果我不上QQ,就不会有人找我打球,我也不会这么忘我的打球....
所以自己还是决定少上QQ为好.

同学都把论文写到了最后一章了,我还在这娱乐......实在是有点儿羞愧......
Entered on [2014-01-08 周三 09:23]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%80%BB%E7%BB%93%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%89][写总结（10分钟）]]
*** 2014-01-09 星期四
**** 专心做好一件事
     真的要坚持一个东西的时候，才发现，真的很难，也可能是做的方法有什么地方不对吧．
     又发现我的任务中有就点不太好的地方．
     1. 每天必做的事情，没有具体到点，所以没有很多早上没有做的事情，就没想去做了．
     2. 太集中到早上的时间了．所以早上做不了真真的任务．
     3. 没有结束的时间，如果真的有事（不是主要任务），让自己一直做，就不容易住手了．．．影响了真正的任务．

现在早起，早睡，是很难做到．这周过后调整自己的计划（利用８０　２０　法则）
1. 早上7:00起,晚上11点睡
2. 7:00　-　7:30　做运动
3. 7:30　-　8:00　读英语
4. 8:00　-　9:00　做思维导图　+　写日记　+　背单词
5. 中午　阅读　+　阅读笔记
6. 晚上10:00　写总结
Entered on [2014-01-09 周四 12:20]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%89][写日记（10分钟）]]
*** 2014-01-11 星期六
**** 做安卓软件
     原本，只是想要汪旭帮我实现这个功能。可是，他就给我做了一半，说后面的反正就是调用数据，调用绘图函数，就好了。我就不帮你弄了。
也是，麻烦了他一天，不过说实话，他效率确实很高，可能各方面熟悉，逻辑又很清晰，所以做起来更快把。
     我没有java基础，也很早就忘记了这个语法严密的语言怎么写了（或者说从来就不曾知道），安卓就更是只看过，没有正式的玩过了。
     硬着头皮上吧，应该不是很难把。。
- 首先，学着怎么添加menu菜单把。。。这个容易，直接在layout中设置就好了，然后设置全局的名字String，要触发的话，就在mainactivity中写个就行了。半天搞定
- 然后就是怎么点击自己建立的menu来弹出新的页面（activity)了。这个，自己居然都是手写的！！从layout，到class，到manifest。。后来才知道android可以直接新建一个activity。。。折腾了半天。这一天就过完了。
  - PS：中间还了解了他的代码，用去不长的时间。
- 现在得找个画图的东西了，于是浏览网页，找到了个别人写好的Canvas.draw的直方图，饼状图等的函数，用用吧。还行，都显示出来了，能够设置的东西也还是有的。
可是后来发现，不全，很多属性的设置不满足我的要求，这样折腾了一天。
- 又忽然记起浏览网页时候看到的制图库（achartengine),那就去了解下把。下载，看看库，又去网上看看别人的中文解释（英文看着慢，我这要速成，没办法）
测试自带的demo，然后黏贴到自己的代码中。成功！ok，看来这个库可以用。（中间了解了下，java怎么插入第三方库）
- 图可以画出来，那就看看数据把，，居然是list<double[]>这，我又不用画几条数据，即使几条数据，那也是后面的事情了。还得考虑怎么把数据转为list<double[]>.
原来用的Array.aslist(double[])发现，得不到我要的结果，得到的是：list(double),不合格。继续试，直接新建list<double[]>，然后add(double[])，OK，
  - ps，
    - 这里记录下，突然Log没用了 ，需要重启eclipse。 
    - 软件总是安装失败，需要project -> clean;
- 接下来就是查看数据库，读取数据了，因为我对数据库一知半解，又没用过sqlite，只好又去看看他的语法，发现，简单的语法，和句子我还都能看懂。直接用把。测试再说。
读取某个值的数据，可以。读取某个时间段的数据。这个要详细说下。
- 时间，存储的格式是string，转为数字是double的。需要利用库（java.calender),或者利用 SimpleDataFormat来识别double为year，month，day，hour，minus
看他原来用的dataformat，照葫芦画瓢，也用了，发现还挺好用的哦。只是想到后面还要经常用，就有点后怕，代码重复的太多了。那就看看Calendar把。。网上有现成的写好的Calendar类，就直接看看，修改下用吧。
- 接着就是弹框的设计。。。查找了android的几种弹框，看到实现都是封装好的，那就直接用把。建立了一个demo，就可以用了，这个很简单。。
但自己在读取数据库数据的时候，没有注意到全局的数组，读取了两次数据库数据，导致一直存在 有未捕获的异常。。。一直折腾了一天。。。记录下，确认数据流，学会设置断点，查看数据。
- 点击menu，弹出弹框，选择选项，弹出新的activity，这几个功能都实现了，现在就是组织数据了。
新建了一个自己数据的格式，将数据库读取的数据，解析成自己的数据格式，最后交给achartengine，就直接绘制出了图片。
- ps：看到别人用图片做统计图（achartengine）背景，我也很感兴趣，就了解了下，原来是设置其他颜色为透明，在layout中添加图片为背景就好了。
哈哈，第一次做了自己的安卓软件。接下来还可以做的：
- 点击添加GPS数据
- 添加日期选择
- 同步到百度云
- 更换背景图片
    
Entered on [2014-01-11 周六 10:47]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%898:15][写日记（10分钟）8:15]]
*** 2014-01-12 星期日
**** github
     
     git是什么：一个分布式的版本控制。
     github是什么？
     git extensions 是什么
     egit 是什么？

     要想装git, 就先要知道这些都是什么东西，干什么用的。。。

比如，git 是核心。。。。基础。。。不管怎么说，先安了这个。。。。

github 是什么，就是一个存放你文件的地方，给你一个ssh地址，你用他来连接你的git

git extensions 是什么，它是为了方便VS使用git 而做的GUI

egit是什么？它是eclipse上的git工具。。。。

git extensions 和 egit 其实都是一个做用。。。。只是用在不同的编辑器。。。

所以你只需要一个 git + (extension | egit) 自己选一个就好了。。。
Entered on [2014-01-12 周日 17:26]
 
 [[file:c:/Users/jerryfive/Desktop/MyDay/README]]
*** 2014-01-13 星期一
**** 做自己想做的，还是很好玩的
     自己有做android的想法，然后就跟汪旭说了，然后就有了现在的事情了。
     开始有导出文件 的功能，但是我可能想重装系统，这样就没有了数据库就没有了，怎么办呢。。
只能导入数据了。。。。
好，那今天 的任务就是怎么导入数据。
思路：
1. 知道原数据库的结构(记录表 + 按钮表）
2. 知道Sqlite的导入方法（同时学了怎么修改数据库表（alter table)
   1. 加入了GPS longitude, altitude列。
3. 知道Java怎么读取Txt数据
   1. 这里需要考虑 中文乱码问题。（文件是什么编码，读取的时候就用什么编码）
4. 知道怎么打开android的文件explorer的方法
   1. 这里用的是Listview 控件。
   2. 要写两个XML文件（一个用来生成ListView，一个用来生成页面）

PS：中间产生的问题
- 乱码问题（中文）utf8编码 or gbk
- Json格式的解析（java的正则很难用）
- 去除重复（用的Set集合）
- timeString 转 SimpleDataFormat 转 Long
- ListView 要有一个单独的XML文件来显示ListView中的内容（simpleAdapter）


Entered on [2014-01-13 周一 22:46]
 
 [[file:d:/cygwin/home/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%898:15][写日记（10分钟）8:15]]
*** 2014-01-15 星期三
**** 折腾
     折腾不是好事。昨天因为Tex一直编译不通过，存在字体不识别的问题，尝试了很多的办法都没有成功。只能考虑，是不是我系统
存在问题？
做好打算，今天来安装Win8，同学都说好用，而且可以直接上网，这是我最关心的问题。。
PS：上次就是因为不能上网被迫改成了Win7 。
找同学错来光盘，拷贝好数据，这就开始吧。。。。
安装很快就结束了。接下来就是软件，又存在很多问题，不能破解Office，不能破解系统，等。。。
最主要的是：不能上网！！！只好跟朱岭发信息，。。。。被BS了下。

做完这些，都到下午了。。。。
可是，突然，又不能上网了！！！

实在受不了了，只好再安Win7 64位。。。。
Win7就是快，，什么东西都很一路顺利。。。没有什么问题。。。
还是不折腾的好。。。

顺便还把github gitExtensions 解决了。。。哈哈。。。
Entered on [2014-01-15 周三 21:35]
 
 [[file:f:/baiduyundownload/emacs/jerryfive/ToDo/newgtd.org::*%E8%A6%81%E5%81%9A%E7%9A%84%E5%9B%BE%E9%83%BD%E5%86%99%E5%A5%BD%E5%9C%B0%E6%96%B9%EF%BC%8C%E8%A6%81%E4%BF%AE%E6%94%B9%EF%BC%8C%E9%83%BD%E5%81%9A%E5%A5%BD%E6%A0%87%E8%AE%B0][要做的图都写好地方，要修改，都做好标记]]
*** 2014-01-16 星期四
**** 存在大脑中的和写下来的，说出来的
     存在大脑中的，也许只有你自己知道，或许你也不是很清楚，只是想当然 的觉得事情应该不是这样的，应该是大脑中想的那样。
可是要你说出个所以然来，你也不能讲清楚。
写下来的，才是你真正知道的。这句话也许不一 定对，但是也有一定的道理：
你的知识如果不能让别人知道，那样的知识只能是提升了你自己，但对于你自己也并没有什么直接的好处。
有的人，厚积薄发，看了一肚子的书，但是什么也说不出来，学了跟没有学也没有什么两样。
有的人，只看了两三本书，可是，确可以说得天花乱缀。
排除人对知识的掌握，至少在外人看来，第二个人懂得更多，也更有话语权。
有的人不善于表达，可以尝试写下来，不管是什么方式，你能说服别人说你懂了这个东西，那才说明，你真的知道了。

现在，看起来，我看了很多东西，但真的要我能写下来，要我能说清楚，这些东西的来龙去脉，真的还是很难的。
现在，我学一个东西，就要真正的知道他是做什么的，应该怎么做，能够写下来，它的执行步骤。

不再看看，认识这些字就过去了。。。
Entered on [2014-01-16 周四 22:16]
 
 [[file:f:/baiduyundownload/emacs/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%898:15][写日记（10分钟）8:15]]
*** 2014-01-19 星期日
**** 有个师弟
     有个师弟，四川的，各种闹腾，说话，我听不太懂，说话，从不注重用词。
     就这样，他基本是实验室中话最多的了。而且跟本不在意别人是否在忙。
     做出了点东西，就开始大呼小叫。
     做不出来东西，也开始不断的报怨。
     不想做了东西，也会止不住的唠叨。
     似乎他就活在自己的世界中，其他人都可以不在乎。。。
     他做好了，他高兴，没做好，不高兴。
     说得好听，那叫：不作做，坦率。
     说得不好，那就是：太自我。。。
     
     他能力是还可以，但做人，还是要多考虑其他人的，
     今天我都想骂他几句了。。。

     深呼吸。。。深呼吸。。。
Entered on [2014-01-19 周日 23:07]
 
 [[file:f:/baiduyundownload/emacs/jerryfive/ToDo/newgtd.org::*%E5%86%99%E6%97%A5%E8%AE%B0%EF%BC%8810%E5%88%86%E9%92%9F%EF%BC%898:15][写日记（10分钟）8:15]]
** 2014-07 七月
*** 2014-07-07 星期一
**** 第二周的第一天班
     组长人还是很不错的，只是自己太过内向了，不太敢表达自己的想法。很多自己想问的都没有说出来。
     第二周的第一天，还是学习，学习C++，学习数据格式协议。
     看着周围的人，都是用的VIM，自己一个人在这里折腾Emacs，总是觉得有点怪怪的，就好比我总觉得自己一个人在用五笔输入法一样。
     
Entered on [2014-07-07 周一 13:53]
 
 [[file:c:/Jerryfive/emacs-24.2/ToDo/newgtd.org::*2014-01%20%E4%B8%80%E6%9C%88][2014-01 一月]]
** 2014-08 八月
*** 2014-08-03 星期日
**** 把时间做朋友（书）
- 把时间当做朋友 :: 李笑来
- 谪要：读书使人完整，讨论使人完备，写作使人完善
- 往往不是因为有兴趣才能做好，而是做好了才产生了兴趣。
- 学习所有东西最好的方法就是：坚持-耐心。
- 心智 = 获得知识 + 应用知识 + 抽象推理
- 不要做自己大脑的奴隶，控制自己的情绪
- 推迟满足感，可以获得更大的满足感
- 基于过程的简单日志（记录每个事件 + 消耗的时间）
- 长期计划，不是一下就可以做到的。试试只做一个月的计划，你可能坚持下来的。
- 效率低下的根本：自动避免困难的事。（我似乎都希望在别人的博客中得到答案，而不是自己从帮助中找到答案）
- 
Entered on [2014-08-03 周日 17:02]
 
 [[file:e:/emacs-24.3/emacs_config/ToDo/newgtd.org::*%E8%AF%84%E4%BB%B7%E7%B3%BB%E7%BB%9F%E7%9A%84%E8%AE%BE%E8%AE%A1][评价系统的设计]]
** 2014-09 九月
*** 2014-09-28 星期日

