#+TITLE: Android大作业心得
#+AUTHOR: zhuxiaolin

* 任务心得
** 学习
每个人都是一个初学都，不想再过多说自己是个Android，Java的初学者。一个任务是对自己学习能力最好的验证。
\\
刚接触这个任务，并没有感觉都太大的压力，只是很多需要去做的东西，心里有一个大概的思路，知道每一步要去做什么，于是赶紧投入了学习状态。
\\
我是个学习不太认真的人，很多时候只是求任务的完成，大体的实现，在学习过程中，也是以完成框架的东西为主，什么东西可以实现这样的需求，什么模式可以更好的应用到这个东西里面。
\\
但做的过程中，会让自己留下很多不太懂的地方，更多的是Bug。所以我要去学着弄懂每一个细节部分。\\
我负责代码的集成，所以在集成组员的代码的时候，我都要让自己去懂他们代码实现的功能，可能出错的地方。
\\
在这样的过程中，我让自己学到了更多的Android细节。
\\
但在遇到问题的时候，还是会慌乱，想要一个老师带我更好的调试代码，分析问题发生的原因。
** 相互合作
与其他同事的合作，让我知道，我写的代码不是一个人在用，我需要兼顾同事的代码。在代码的命名，代码的注释，代码的函数接口，代码的错误判断上都要考虑是不是会对同事的代码造成影响。
\\
在两个方面上需要特别的注意
1. 数据结构 :: 因为数据结构是共同使用的，所以在确定数据结构的时候，要同时考虑到其他模块是否能很好的理解需求。
比如数据组需要同时知道 UI组和 Server的数据结构，以便为他们提供正确的解析操作。
1. 接口 :: 在定义函数的时候，要考虑其他模式是不是会需要利用你的函数去做一些事，所以在函数的定义参数，返回值的选择上要更小心。
2. 需要特别指出的是：
   - 我在没有经过大家讨论的情况下，增加了拨打电话的功能，这点我要表示道歉。
   - 功能的定义，功能的增加，应该经过所有组员的同意才是。
** 任务汇报
及时汇报自己的工作进度是一个很好的习惯。这点我自认为没有做得很好。
\\ 
我总是在试图完成每个功能，做完软件后才去汇报自己的工作。所以在时间节点的划分时候，没能做到按时完成。
\\
* 组长心得
** 任务分配
需要对任务做了一个大方向准确的划分，但是在工作量的分析上没有做好。
在知道任务分工不平衡的时候没有实时的做出调整，合理的让每个人都学到更多的东西。这是我的失职。

** 责任
作为一个组长，首要目的是带领团队去完成一个任务，去更好的完成这个任务。\\
在完成这个任务上，我做到了，但在更好的完成这个任务上，我做得不好，没有给组员传递一个追求更高品质成果的理念。
\\
尤其是在后期，更是忙着修补一个个因前期任务交待不清楚留下的Bug。没有考虑让任务更加的完善。
** 分享
在任务完成后，应该开一个会，让每个人都来讲讲自己做的东西，这一点我没有做。
- 一是将自己的知识分享给每个人。
- 二是总结任务过程中，自己觉得自己做得好的，不好的。别人（组长）做得不好的地方。大家相互提升。


